# Generated by Django 4.2 on 2023-04-28 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ip', models.GenericIPAddressField()),
                ('data', models.DateField()),
                ('banco', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedata.emprestimo')),
            ],
        ),
    ]
