# Generated by Django 4.2 on 2023-04-29 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onedata', '0004_alter_pagamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
